<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tài khoản nhận tiền</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>680be40d-51df-4823-8b4b-60e3165d55e6</testSuiteGuid>
   <testCaseLink>
      <guid>e387844b-f0a4-4268-ae52-b071770c0efb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/1. Kiểm tra chức năng tìm kiếm tại màn hình Quản lý tài khoản nhận</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>af829c21-4b7d-4d60-a58c-41fcbbf82b27</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TKNHanTien</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>af829c21-4b7d-4d60-a58c-41fcbbf82b27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>account</value>
         <variableId>bada0e7e-c806-42bf-b5d4-ca57d8a3a1ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af829c21-4b7d-4d60-a58c-41fcbbf82b27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quocgia</value>
         <variableId>71c71be4-ce10-4c95-84f4-a5d277539a79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af829c21-4b7d-4d60-a58c-41fcbbf82b27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tennganhang</value>
         <variableId>9d388b71-f3e7-45a1-a2a4-ae2398daaa1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af829c21-4b7d-4d60-a58c-41fcbbf82b27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>stk</value>
         <variableId>e014d16c-aff6-4ac7-b44b-4fc88cce35ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af829c21-4b7d-4d60-a58c-41fcbbf82b27</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>validateRessult</value>
         <variableId>c3b5b8b6-83d0-4579-994b-2b13a2717e41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e190f054-e245-4063-be3a-ba21b100e1a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/2.Kiểm tra click reset bộ lọc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1f92c7b7-1482-411d-8616-54c2448e1f14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/3.Verify màn hình thêm tài khoản nhận tiền không hợp lệ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed15739d-b9aa-4937-9c53-d3a2f095dcd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>675ac2e3-e870-4977-93a9-d410e25c6a6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de5e9d72-dde5-44ec-9f06-47b17ba1b496</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1908592c-4219-48d3-801c-d8c779042919</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/4. Kiểm tra tạo yêu cầu tài khoản nhận tiền thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>00302fa3-4f6c-4011-9c54-1166c20e1439</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/5. Kiểm tra tạo yêu câu tài khoản nhân tiền không thành công do đã tồn tại tài khoản đang chờ duyệt</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>768f5024-3060-4c8d-890f-0adcc8798a32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/6. Kiểm tra huỷ yêu cầu tạo tài khoản nhận tiền</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>875f390f-1701-4bbc-a504-01e6d07bea97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/7.Kiêm tra tài khoản có trạng thái hoạt động</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>817b214b-9b6a-46fa-aade-cb8be8c0a3fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/8.Kiểm tra tài khoản có trạng thái không hoạt động</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>95eafcb4-e31e-4733-8df0-55da84765f09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/9. Kiểm tra hiển thị ngân hàng nhận tiền đã thêm hiển thị tại mục Rút tiền CMS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cb2ffc6d-b0e5-400f-a3eb-ec9d1dd1cb18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/QLyTKNhanTien/10. Kiểm tra hiển thị ngân hàng nhận tiền đã thêm hiển thị tại mục rút tiền MCV</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
