<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_status</name>
   <tag></tag>
   <elementGuidId>c000faaa-567c-4855-94fd-80913daf7ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='partner_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;partner_status&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0913eeaa-5124-48ab-a8e2-13f0bafdf1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>partner_status</value>
      <webElementGuid>103b2cd6-8d22-462e-aaca-1a10b3981e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Trạng thái</value>
      <webElementGuid>880aac21-716f-4d4e-8f29-d316a312df52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select custom-select-lg</value>
      <webElementGuid>cc567b34-5429-4548-bb17-2acb33e3d3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toàn bộ Đang hoạt động Không hoạt động</value>
      <webElementGuid>cef566d1-7e24-4446-9220-675d91b32b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/main[@class=&quot;main-content&quot;]/div[1]/div[2]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm-3 col-xl-2&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;custom-select custom-select-lg&quot;]</value>
      <webElementGuid>b21260df-70b6-486c-b748-768bc3c33c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='partner_status']</value>
      <webElementGuid>df098c00-d93a-4ef2-b178-e26ff467b657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/main/div/div[2]/div/div/div/div[2]/div/form/div/div[2]/div/select</value>
      <webElementGuid>cd566a87-4ca7-44ef-be8a-78bb2b30823c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7cae05ef-4da1-4fbb-87f4-701a6e68f635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'partner_status' and @title = 'Trạng thái' and (text() = 'Toàn bộ Đang hoạt động Không hoạt động' or . = 'Toàn bộ Đang hoạt động Không hoạt động')]</value>
      <webElementGuid>825c8de5-0468-42a8-92d5-3e4f34e9a635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
