<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_QuanlyGD</name>
   <tag></tag>
   <elementGuidId>8736a057-718c-4aa4-9d9b-0116495287e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='report']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#report > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c9bdacf-5af0-402b-8539-b66249e7a740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5ef80d77-4c8e-4c20-a3a5-5ecc8ea7254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Quản lý giao dịch</value>
      <webElementGuid>c388f0b3-9ca2-4232-ae4d-8dded586a4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report&quot;)/a[1]</value>
      <webElementGuid>22057bfd-b507-44f9-9f66-31a97a8b1e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='report']/a</value>
      <webElementGuid>b403da54-333e-4afe-a613-92630f7504a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quản lý giao dịch')]</value>
      <webElementGuid>b96ee8f0-6328-4dd9-9ef6-3859bdf6c9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>381cabb6-00bd-46da-8420-956a49bd11bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/a</value>
      <webElementGuid>2bd334a6-593b-438d-ad14-4b605c451a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '  Quản lý giao dịch' or . = '  Quản lý giao dịch')]</value>
      <webElementGuid>2799ad7c-b7f0-4e7c-a655-6fd8228b70c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
