<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Qun l s d</name>
   <tag></tag>
   <elementGuidId>1993eed4-809a-4f15-81fe-57eef6dd6675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='deposit_withdrawal']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deposit_withdrawal > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9dd132cb-7b4c-4fcb-9706-401e485e142d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>da367495-e4c9-4431-8e69-b9e158cd2e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Quản lý số dư</value>
      <webElementGuid>3a01f31f-f245-4c0f-843a-d0f63398a227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deposit_withdrawal&quot;)/a[1]</value>
      <webElementGuid>90d38f7a-8552-4f41-92c3-1732cc90fbb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='deposit_withdrawal']/a</value>
      <webElementGuid>fc6437b8-ba21-4a3a-b483-231608b667dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quản lý số dư')]</value>
      <webElementGuid>7be8523d-5942-444f-bdb9-d22ccbf95dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>d705a2f5-6cb2-4b64-9eae-6a17c6e6ebaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a</value>
      <webElementGuid>da2bd9bc-6fdb-48ef-a1f4-6345b7b33397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '  Quản lý số dư' or . = '  Quản lý số dư')]</value>
      <webElementGuid>5ec4fda6-490e-4460-ad38-6f8d594ab148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
