<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ti khon ch                                                             autotest</name>
   <tag></tag>
   <elementGuidId>9ff7eabd-96e7-4703-9150-5e18b2ab4dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='user_target_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;user_target_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf97cb07-1879-42df-a1a5-15f2dbe6f5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_target_id</value>
      <webElementGuid>daba4984-0b49-4ebc-a619-30604c8564b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a5259fcf-20ad-4e95-a473-bd0c15690a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tài khoản đích
                                                             autotest</value>
      <webElementGuid>1ace8558-49a5-4181-90b1-ebd7f5a7fa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3aec9f84-4c0b-47e3-9dc3-7dfc898ce1d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='user_target_id']</value>
      <webElementGuid>97f58376-f83e-43f1-b3f5-445a9dd726a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_form']/div/div[2]/div/select</value>
      <webElementGuid>1612cf57-26e5-4d1a-aedb-17bc05d89081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>eb558969-bed1-4783-a133-41c86abc68a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user_target_id' and (text() = 'Tài khoản đích
                                                             autotest' or . = 'Tài khoản đích
                                                             autotest')]</value>
      <webElementGuid>ed453250-0a80-4863-ad21-55cd46e43aa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
