<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DropdownlistChonNH</name>
   <tag></tag>
   <elementGuidId>ae9200f0-c7eb-4d69-946a-7be4f4595401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-bank_code-1n-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-bank_code-1n-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2bb492c-5b4a-4070-9e13-a838e8ec401d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>8ccdc3d8-91d8-4091-8354-f99def88b53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-bank_code-1n-container</value>
      <webElementGuid>8fe16362-1127-4c3c-b074-c39cd2866f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chọn ngân hàng</value>
      <webElementGuid>51238d2f-87d3-4f7e-af1a-74254e4ff14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn ngân hàng</value>
      <webElementGuid>64bd2ea8-4f5f-421a-8e97-b93a89cbf6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-bank_code-1n-container&quot;)</value>
      <webElementGuid>b744ec91-7283-4e7f-976f-4419064ab47e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-bank_code-1n-container']</value>
      <webElementGuid>6a54bf37-238c-4e2f-8d62-78a2009dbf2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refundModal']/div/div/div[2]/form/div/div/div/span/span/span/span</value>
      <webElementGuid>1ccc1e9c-bf0c-43f0-bc34-87a6945afc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[1]/following::span[4]</value>
      <webElementGuid>5e0c2191-97e9-4eb2-9db0-742a479a61ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngân hàng'])[1]/following::span[4]</value>
      <webElementGuid>c9cd00ca-dfb2-4e16-b862-b699f9b61f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại tài khoản'])[1]/preceding::span[3]</value>
      <webElementGuid>29e268c8-8c2c-48b1-8468-bfa87af2adf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[2]/preceding::span[3]</value>
      <webElementGuid>33778ce2-c4ff-4e83-9ce6-a17c5c5ba48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/span/span/span/span</value>
      <webElementGuid>14820e3a-d19a-49e3-933f-03c4e02eec81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-bank_code-1n-container' and @title = 'Chọn ngân hàng' and (text() = 'Chọn ngân hàng' or . = 'Chọn ngân hàng')]</value>
      <webElementGuid>5e8e57be-797b-4ee9-a26a-fdd5c0852ad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
