<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Chonnganhang</name>
   <tag></tag>
   <elementGuidId>3c7aef26-1550-45d8-bfd0-bf1da1c4a8a7</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(@title,'Chọn ngân ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-bank_code-au-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'select2-bank_code-au-container' and @title = 'Chọn ngân hàng' and (text() = 'Chọn ngân hàng' or . = 'Chọn ngân hàng')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8cfa6774-eb92-4042-8f11-55c211283692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>0c0ef84d-5426-4842-ba96-e9e4dad1abb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-bank_code-au-container</value>
      <webElementGuid>943015a5-dd9d-414a-833c-e1163e313edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chọn ngân hàng</value>
      <webElementGuid>6a4c9d2f-7b99-4c7a-a1f0-399c63d683ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn ngân hàng</value>
      <webElementGuid>77e663fd-475e-4934-a089-76467d1b3ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-bank_code-au-container&quot;)</value>
      <webElementGuid>b4a93397-ade2-4973-85a3-a1adb96257da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-bank_code-au-container']</value>
      <webElementGuid>822b6165-4da6-49e7-b15c-9690773570e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='refundModal']/div/div/div[2]/form/div/div/div/span/span/span/span</value>
      <webElementGuid>c3abc59a-c1c8-4e69-91d7-0291589f6007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[1]/following::span[4]</value>
      <webElementGuid>996a4643-9a14-426b-ba05-e7b6f6350a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngân hàng'])[1]/following::span[4]</value>
      <webElementGuid>7cd5bb99-a3b1-49c6-91ae-c6f40269e37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loại tài khoản'])[1]/preceding::span[3]</value>
      <webElementGuid>fe17b47c-c495-4c42-9cb7-1e97d423cc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(*)'])[2]/preceding::span[3]</value>
      <webElementGuid>0641b580-69e5-4eb8-9bd0-ee8d8ee94abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/span/span/span/span</value>
      <webElementGuid>6b2cdb40-9325-47e3-80dc-75eecb0f9865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-bank_code-au-container' and @title = 'Chọn ngân hàng' and (text() = 'Chọn ngân hàng' or . = 'Chọn ngân hàng')]</value>
      <webElementGuid>d23c10f1-c9b2-42ec-872a-c9d4629d4d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
